name: DenmarkAddresses
main: com.instancedev.addresses.Main
version: 1.1
author: instancelabs
commands:
   address:
      description: Main command
      usage: /address
      aliases: [atp, at]
   addpoints:
      description: Main command
      usage: /addpoints
      aliases: [atpaddpoints]
